name: Environment Variables
on: push
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            BRANCH: ${ { github.ref_name } }   # 環境変数BRANCHにブランチ名を設定
        steps:
            - run: echo "${BRANCH}"         # 環境変数BRANCHの値を表示
            - uses: actions/checkout@v4
